[build]
  base = "website/"
  publish = "build"
  command = "yarn build"
  environment = { NODE_VERSION = "14" }

[context.production]
  command = "yarn run crowdin:sync && yarn build"

[context.deploy-preview]
  command = "yarn build"

[[redirects]]
from = "https://docs.taichi.graphics/*"
to = "https://docs.taichi-lang.org/:splat"
status = 301
force = true

[[redirects]]
  from = "/lang/articles/:slug"
  to = "/docs/:slug"
  status = 301
[[redirects]]
  from = "/lang/articles/:dir/:slug"
  to = "/docs/:slug"
  status = 301
